bs:
  time:
    format: yyyy年MM月dd日
  jdbctemplate:
    url: jdbc:mysql://localhost:3306/db_mybatis
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: #It is generally referred to root
    pwd: #Your password
  attrbuties:
logging:
  level:
    root: debug
    org.springframework.web: error
    org.apache: error
  logback:
    rollingpolicy:
      max-file-size: 1MB
  file:
    name: info.log