spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
      file-size-threshold: 20MB
  web:
    resources:
      static-locations: [ classpath:/static/, classpath:/public, classpath:/resources, classpath:/webapp, file:D:/upload/ ]
  redis:
    #spring.redis.database: 0：指定连接Redis时使用的数据库，默认为0。
    database: 0
    #spring.redis.port: 6379：指定Redis服务器的端口号，默认为6379。
    port: 6379
    lettuce:
      pool:
        #spring.redis.lettuce.pool.max-idle: 8：指定连接池中的最大空闲连接数，默认为8。
        max-idle: 8
        #spring.redis.lettuce.pool.min-idle: 0：指定连接池中的最小空闲连接数，默认为0。
        min-idle: 0
        #spring.redis.lettuce.pool.max-active: 8：指定连接池中的最大活动连接数，默认为8。
        max-active: 8
        #spring.redis.lettuce.pool.max-wait: -1ms：指定从连接池中获取连接时的最大等待时间，默认为-1ms，表示无限等待。
        max-wait: -1ms
        #spring.redis.timeout: 180：指定与Redis服务器建立连接的超时时间，单位为秒，默认为180秒。
    timeout: 180
  session:
    #session存储方式:session
    store-type: redis
  mail:
    default-encoding: utf-8
    # 发件服务器地址,不同邮件平台地址不同
    host: smtp.qq.com
    #端口一般为465 587
    port: 587
    #发送邮箱的账号
    username:
    #你的授权码,请在qq邮箱申请
    password:
    #发送邮件账号的授权码,这里的授权码不是验证码.需要到邮箱获取
    protocol: smtp
    #设置是否在启动时测试与邮件服务器的连接。若设置为true，在应用程序启动时，会尝试与邮件服务器建立连接并进行测试。
    test-connection: true
    #设置其他邮件相关的属性
    properties:
      properties:
        #设置与邮件服务器建立连接的超时时间，以毫秒为单位。
        timeout: 5000
        #设置连接邮件服务器的超时时间，以毫秒为单位
        connection-timeout: 5000
        #设置写入邮件服务器的超时时间，以毫秒为单位。
        write-timeout: 5000
        #设置是否启用 SMTP 认证，用于验证发送邮件的身份。
        mail.smtp.auth: true
        #设置是否启用 STARTTLS，当使用加密连接时需要启用。
        mail.smtp.starttls.enable: true
        #设置是否要求启用 STARTTLS。启用后，若邮件服务器不支持 STARTTLS，则连接将被拒绝。
        mail.smtp.ssl.enable: true
        # 设置是否显示发送邮件的日志。
        mail.display.sendemail: spring-boot-demo

server:
  port: 81







