spring:
#  redis:
#    database: 0
#    port: 6379
#    lettuce:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1ms
#    timeout: 180
#  session:
#    store-type: redis
server:
#  additionalPorts:
  port: 81
