spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效
  profiles:
    active: "prod"
blo:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db_mybatis
  username: #It is generally referred to root
  password: #Your password

logging:
  level:
    root: debug
    org.springframework.web: error
    org.apache: error

  logback:
    rollingpolicy:
      max-file-size: 1MB
  file:
    name: info.log
